// Shared by UI and Edge. Only the Edge determines the effective operation/price.
export const CREDIT_CATALOG = Object.freeze({
 ESTUDO_DE_CASO:3, PAEE:3, PEI:3, PDI:3, DOCUMENTO_UNICO_PAEE_PEI:5,
 PERFIL_INTELIGENTE:6, PLANO_REGENTE:6, PLANO_AEE:7,
 RELATORIO_ECONOMICO:1, RELATORIO_PADRAO:2, RELATORIO_PREMIUM:4, RELATORIO_INSS:4,
 FICHA_PEDAGOGICA_REGENTE:2, PARECER_CUIDADORA:2, CHECKLIST_ANALISE:3,
 ANALISE_DOCUMENTO:3, IMPORTAR_DOCUMENTO_TEXTO:3, IMPORTAR_DOCUMENTO_VISUAL:5,
 UPLOAD_MODELO:5, ANALISAR_MODELO_DOCX:5, OCR:1, SUGESTAO_PEDAGOGICA:1,
 INCLUILAB_ECONOMICO:2, INCLUILAB_VISUAL:8, INCLUILAB_PREMIUM:15,
 INCLUILAB_ADAPTAR_ECONOMICO:2, INCLUILAB_ADAPTAR_VISUAL:8, INCLUILAB_ADAPTAR_PREMIUM:15,
} as const);
export type CreditOperation = keyof typeof CREDIT_CATALOG;
const aliases: Record<string,CreditOperation> = {
 ESTUDO_CASO:'ESTUDO_DE_CASO', ESTUDO_DE_CASO:'ESTUDO_DE_CASO',
 DOCUMENTO_UNIFICADO_PEI_PAEE:'DOCUMENTO_UNICO_PAEE_PEI', DOCUMENTO_UNICO_PAEE_PEI:'DOCUMENTO_UNICO_PAEE_PEI',
 'DOCUMENTO ÚNICO PAEE + PEI':'DOCUMENTO_UNICO_PAEE_PEI',
 'DOCUMENTO UNIFICADO PEI + PAEE':'DOCUMENTO_UNICO_PAEE_PEI',
 'ESTUDO DE CASO':'ESTUDO_DE_CASO','PLANO DE AÇÃO AEE':'PLANO_AEE',
 PLANO_ACAO:'PLANO_REGENTE',PLANO_ACAO_AEE:'PLANO_AEE',
 PLANO_ACAO_REGENTE:'PLANO_REGENTE',RELATORIO:'RELATORIO_PADRAO',ATIVIDADE:'INCLUILAB_ECONOMICO',
 ATIVIDADE_IMAGEM:'INCLUILAB_PREMIUM',ADAPTAR_ATIVIDADE:'INCLUILAB_ADAPTAR_ECONOMICO',
 EDULEISIA_ADAPTAR:'INCLUILAB_ADAPTAR_ECONOMICO',EDULEISIA_IMAGEM:'INCLUILAB_PREMIUM',NEURODESIGN_REDESIGN:'INCLUILAB_ADAPTAR_ECONOMICO',NEURODESIGN_IMAGEM:'INCLUILAB_PREMIUM',
 ANALYZE_DOCUMENT:'ANALISE_DOCUMENTO',ANALYZE_UPLOADED_DOC:'ANALISE_DOCUMENTO',
 CHECKLIST_OCR:'CHECKLIST_ANALISE',CHECKLIST_SCAN_ENEM:'CHECKLIST_ANALISE',
 CHECKLIST_PARECER:'FICHA_PEDAGOGICA_REGENTE',CUIDADORA_PARECER:'PARECER_CUIDADORA',
 DOCUMENT_IMPORT:'IMPORTAR_DOCUMENTO_TEXTO',DOCUMENT_IMPORT_VISUAL:'IMPORTAR_DOCUMENTO_VISUAL',
 REPORT_ECONOMICO:'RELATORIO_ECONOMICO',REPORT_PADRAO:'RELATORIO_PADRAO',REPORT_PREMIUM:'RELATORIO_PREMIUM',
 REPORT_INSS:'RELATORIO_INSS',REPORT_GEMINI_FLASH:'RELATORIO_ECONOMICO',
 REPORT_GEMINI_PRO:'RELATORIO_PADRAO',REPORT_GPT4O:'RELATORIO_PREMIUM',
 ACTIVITY:'INCLUILAB_ECONOMICO',ACTIVITY_STRUCTURED:'INCLUILAB_ECONOMICO',
 ADAPT_ACTIVITY:'INCLUILAB_ADAPTAR_ECONOMICO',INCLUILAB_ACTIVITY_SCHEMA:'INCLUILAB_ECONOMICO',
 INCLUILAB_IMAGE:'INCLUILAB_PREMIUM',ACTIVITY_IMAGE:'INCLUILAB_PREMIUM',
 TEMPLATE:'UPLOAD_MODELO',
};
export function canonicalOperation(value: unknown): CreditOperation {
 const raw=String(value??'').trim().toUpperCase().replace(/^PROTOCOL_/,'');
 const code=aliases[raw]??raw;
 if(!Object.prototype.hasOwnProperty.call(CREDIT_CATALOG,code)) throw new Error(`UNKNOWN_CREDIT_OPERATION:${raw}`);
 return code as CreditOperation;
}
export function creditCost(value: unknown): number { return CREDIT_CATALOG[canonicalOperation(value)]; }
export function serverCreditOperation(payload: {operation?: unknown;requestType?: unknown;task?: unknown;documentType?: unknown;targetDocType?: unknown}) {
 const code=canonicalOperation(payload.operation??payload.requestType);
 if(payload.requestType && canonicalOperation(payload.requestType)!==code)throw new Error('OPERATION_REQUEST_MISMATCH');
 if(payload.targetDocType && canonicalOperation(payload.targetDocType)!==code)throw new Error('OPERATION_TARGET_MISMATCH');
 if(payload.documentType && canonicalOperation(payload.documentType)!==code)throw new Error('OPERATION_DOCUMENT_MISMATCH');
 if(payload.task==='image'&&!['INCLUILAB_VISUAL','INCLUILAB_PREMIUM','INCLUILAB_ADAPTAR_VISUAL','INCLUILAB_ADAPTAR_PREMIUM'].includes(code))throw new Error('OPERATION_TASK_MISMATCH');
 return {code,cost:CREDIT_CATALOG[code]};
}
